external.settings:
  type: mapping
  label: Settings
  mapping:
    external_enabled:
      type: boolean
    external_docs_enabled:
      type: boolean
    external_disabled_patterns:
      type: string
